### PR TITLE
ANUJAGRAWAL2000 Keyboard

### PR DESCRIPTION
**Pull request by ANUJAGRAWAL2000**

### CODE REVIEW

**Review by krharsh17 — CHANGES_REQUESTED** [review]
Rename `KEYBOARD.html` to `index.html` otherwise your page will not work when hosted.

**Comment by ANUJAGRAWAL2000** [comment]
> Rename `KEYBOARD.html` to `index.html` otherwise your page will not work when hosted.

Sir,To rename this html file I have to create the repository again or i can change in the previous ones..

**Comment by krharsh17** [comment]
You can change in this PR only. Just rename the file locally on your computer, create a new commit and push it to the same repo which you had done earlier. It will be automatically updated.

**Comment by ANUJAGRAWAL2000** [comment]
> You can change in this PR only. Just rename the file locally on your computer, create a new commit and push it to the same repo which you had done earlier. It will be automatically updated.

sir i renamed the file locally and also create a commit for that but when i am pushing it then it is showing this.
To https://github.com/ANUJAGRAWAL2000/HACKSLASH-2-Keyboard.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/ANUJAGRAWAL2000/HACKSLASH-2-Keyboard.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Please  tell me ..what should i do now..

**Review by krharsh17 — APPROVED** [review]

**Comment by krharsh17** [comment]
@ANUJAGRAWAL2000 you could try pulling the remote changes using
```
git pull origin master
```

However, I've made the required change in your code and merged it. Please try this the next time.

**Pull request merged**
